---
- name: Setup all servers
  hosts: development
  become: true
  become_method: sudo
  gather_facts: true
  vars:
    ansible_become_password: 123456
  roles:
    - update
    - docker_install
    # - nodejs
    # - python
  

- name: Docker login
  hosts: development
  become: true
  gather_facts: true
  vars:
    ansible_become_password: 123456
  roles:
    - docker_login


- name: Docker build
  hosts: development
  become: true
  gather_facts: true
  vars:
    ansible_become_password: 123456
  roles:
    - docker_build

- name: Docker push
  hosts: development
  become: true
  gather_facts: true
  vars:
    ansible_become_password: 123456
  roles:
    - docker_push


- name: Docker pull
  hosts: development
  become: true
  gather_facts: true
  vars:
    ansible_become_password: 123456
  roles:
    - docker_pull

- name: Deploy
  hosts: development
  become: true
  gather_facts: true
  vars:
    ansible_become_password: 123456
  roles:
    - docker_compose

